### ISSUE TITLE
strange looking/appearance

### ISSUE THREAD

**Issue by bcube2** [molarmanful/gCube#10] opened 2015-08-19 10:44 UTC
This is how I see the simulators:

![something-is-wrong](https://cloud.githubusercontent.com/assets/12406850/9354340/f45439d6-466f-11e5-966c-79b0230c3aa7.jpg)

**Comment by mikebolt** [comment] 2015-08-19 15:12
Can you give us some information about your system, like the operating system, browser, browser version, and any relevant browser plugins/extensions? The current release is known to be broken for Internet Explorer.

**Comment by bcube2** [comment] 2015-08-19 15:40
Notebook, Win 7, FF 39, no special extensions. After several refreshes the simulators began to appear as expected (besides the bottom one in the middle which reminds me Fisher Cube. It is cute ;-) ).

**Comment by mikebolt** [comment] 2015-08-20 04:58
I'm not sure what went wrong, but I'm guessing that you had an old version of the code in your cache. It is also possible that the gcube-min.js was not rebuilt when it should have been. I'm hoping to set up a bot that will do that for us.

I'm going to close this for now, but please reopen it if you find a way to reproduce the issue.

Also, thanks for reporting this. Please keep poking around and trying to break things :)

**Closed as completed** 2015-08-20 04:58 UTC
Labels: bug

**Comment by bcube2** [comment] 2015-08-24 06:04
As I was saying, after several refreshes the simulators are as expected (in terms of appearance) except for the bottom one in the middle - no matter how much refreshes, it always has a shape of the Fisher Cube. But since it is called gCube Entropy, maybe it is correct shape after all... 

offtopic
I don´t know how to reopen the issue
/offtopic

**Comment by mikebolt** [comment] 2015-08-24 06:12
I think it's supposed to look like that. Check out the code:

```
$('g-cube').gscramble('/random');
cube.twist(new ERNO.Twist('U', 20));
cube.twist(new ERNO.Twist('R', 20));
cube.twist(new ERNO.Twist('D', 20));
cube.twist(new ERNO.Twist('L', 20));
cube.twist(new ERNO.Twist('F', 20));
cube.twist(new ERNO.Twist('B', 20));
```

This means that it scrambles the cube then rotates each face clockwise by 20 degrees. The effect is that all the cubelets are twisted. It still works somehow, but it's not super pretty because the faces clip through eachother.

I think you have to have write access to manage issues.

**Comment by bcube2** [comment] 2015-08-24 15:59
Okay then, thank you for an explanation regarding Entropy.

My ambition was not reopening this issue, do not get me wrong. It was just a general statement. Still no idea how to get an access (which is not needed for me I guess) ;-)
